name: Push Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build, Test, and Push
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Create .env file for Docker Compose
        run: |
          touch .env
          grep -qF 'POSTGRES_DB' .env || echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          grep -qF 'POSTGRES_USER' .env || echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          grep -qF 'POSTGRES_PASSWORD' .env || echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

      -
        name: Set up Docker Build for caching availability
        uses: docker/setup-buildx-action@v3

      -
        name: Install Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      -
        name: Run tests
        run: make ci

      -
        name: Build and push production image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-for-programmers-project-74:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/devops-for-programmers-project-74:latest
          cache-to: type=inline,ref=${{ secrets.DOCKER_USERNAME }}/devops-for-programmers-project-74:latest